"""Auto-generated stub file for the main window."""
#  MIT Licence
#  Copyright (c) 2024 Asger Jon Vistisen
from __future__ import annotations

from enum import EnumType
from types import FunctionType as function

from PySide6.QtCore import QMetaObject, Signal
from PySide6.QtGui import QAction
from PySide6.QtWidgets import QMainWindow

from OLDmorevistutils.fields import Later

method_descriptor = type(QMainWindow.addDockWidget)
classmethod_descriptor = type(classmethod)


class MainWindow(QMainWindow):
  """The main application window class."""

  # Defined Actions:
  new: QAction
  open: QAction
  save: QAction
  saveAs: QAction
  eXIT: QAction

  # Namespace contribution from MainWindow
  showActions: function
  mouseReleaseEvent: function
  createActionStub: function
  connectActions: function
  staticMetaObject: QMetaObject

  # Namespace contribution from LayoutWindow
  baseWidget: Later
  baseLayout: Later
  welcomeLabel: Later
  goodbyeLabel: Later
  initUI: function
  connectActions: function
  staticMetaObject: QMetaObject

  # Namespace contribution from BaseWindow
  mainMenuBar: Later
  addAction: function
  initUI: function
  connectActions: function
  createActionStub: function
  show: function
  aboutPython: function
  staticMetaObject: QMetaObject

  # Namespace contribution from QMainWindow
  addDockWidget: method_descriptor
  addToolBar: method_descriptor
  addToolBarBreak: method_descriptor
  centralWidget: method_descriptor
  contextMenuEvent: method_descriptor
  corner: method_descriptor
  createPopupMenu: method_descriptor
  dockOptions: method_descriptor
  dockWidgetArea: method_descriptor
  documentMode: method_descriptor
  event: method_descriptor
  iconSize: method_descriptor
  insertToolBar: method_descriptor
  insertToolBarBreak: method_descriptor
  isAnimated: method_descriptor
  isDockNestingEnabled: method_descriptor
  isSeparator: method_descriptor
  menuBar: method_descriptor
  menuWidget: method_descriptor
  removeDockWidget: method_descriptor
  removeToolBar: method_descriptor
  removeToolBarBreak: method_descriptor
  resizeDocks: method_descriptor
  restoreDockWidget: method_descriptor
  restoreState: method_descriptor
  saveState: method_descriptor
  setAnimated: method_descriptor
  setCentralWidget: method_descriptor
  setCorner: method_descriptor
  setDockNestingEnabled: method_descriptor
  setDockOptions: method_descriptor
  setDocumentMode: method_descriptor
  setIconSize: method_descriptor
  setMenuBar: method_descriptor
  setMenuWidget: method_descriptor
  setStatusBar: method_descriptor
  setTabPosition: method_descriptor
  setTabShape: method_descriptor
  setToolButtonStyle: method_descriptor
  setUnifiedTitleAndToolBarOnMac: method_descriptor
  splitDockWidget: method_descriptor
  statusBar: method_descriptor
  tabPosition: method_descriptor
  tabShape: method_descriptor
  tabifiedDockWidgets: method_descriptor
  tabifyDockWidget: method_descriptor
  takeCentralWidget: method_descriptor
  toolBarArea: method_descriptor
  toolBarBreak: method_descriptor
  toolButtonStyle: method_descriptor
  unifiedTitleAndToolBarOnMac: method_descriptor
  DockOption: EnumType
  tabifiedDockWidgetActivated: Signal
  iconSizeChanged: Signal
  toolButtonStyleChanged: Signal
  staticMetaObject: QMetaObject

  # Namespace contribution from QWidget
  acceptDrops: method_descriptor
  accessibleDescription: method_descriptor
  accessibleName: method_descriptor
  actionEvent: method_descriptor
  actions: method_descriptor
  activateWindow: method_descriptor
  addAction: method_descriptor
  addActions: method_descriptor
  adjustSize: method_descriptor
  autoFillBackground: method_descriptor
  backgroundRole: method_descriptor
  backingStore: method_descriptor
  baseSize: method_descriptor
  changeEvent: method_descriptor
  childAt: method_descriptor
  childrenRect: method_descriptor
  childrenRegion: method_descriptor
  clearFocus: method_descriptor
  clearMask: method_descriptor
  close: method_descriptor
  closeEvent: method_descriptor
  contentsMargins: method_descriptor
  contentsRect: method_descriptor
  contextMenuEvent: method_descriptor
  contextMenuPolicy: method_descriptor
  create: method_descriptor
  createWinId: method_descriptor
  createWindowContainer: staticmethod
  cursor: method_descriptor
  destroy: method_descriptor
  devType: method_descriptor
  dragEnterEvent: method_descriptor
  dragLeaveEvent: method_descriptor
  dragMoveEvent: method_descriptor
  dropEvent: method_descriptor
  effectiveWinId: method_descriptor
  ensurePolished: method_descriptor
  enterEvent: method_descriptor
  event: method_descriptor
  find: staticmethod
  focusInEvent: method_descriptor
  focusNextChild: method_descriptor
  focusNextPrevChild: method_descriptor
  focusOutEvent: method_descriptor
  focusPolicy: method_descriptor
  focusPreviousChild: method_descriptor
  focusProxy: method_descriptor
  focusWidget: method_descriptor
  font: method_descriptor
  fontInfo: method_descriptor
  fontMetrics: method_descriptor
  foregroundRole: method_descriptor
  frameGeometry: method_descriptor
  frameSize: method_descriptor
  geometry: method_descriptor
  grab: method_descriptor
  grabGesture: method_descriptor
  grabKeyboard: method_descriptor
  grabMouse: method_descriptor
  grabShortcut: method_descriptor
  graphicsEffect: method_descriptor
  graphicsProxyWidget: method_descriptor
  hasFocus: method_descriptor
  hasHeightForWidth: method_descriptor
  hasMouseTracking: method_descriptor
  hasTabletTracking: method_descriptor
  height: method_descriptor
  heightForWidth: method_descriptor
  hide: method_descriptor
  hideEvent: method_descriptor
  initPainter: method_descriptor
  inputMethodEvent: method_descriptor
  inputMethodHints: method_descriptor
  inputMethodQuery: method_descriptor
  insertAction: method_descriptor
  insertActions: method_descriptor
  internalWinId: method_descriptor
  isActiveWindow: method_descriptor
  isAncestorOf: method_descriptor
  isEnabled: method_descriptor
  isEnabledTo: method_descriptor
  isFullScreen: method_descriptor
  isHidden: method_descriptor
  isLeftToRight: method_descriptor
  isMaximized: method_descriptor
  isMinimized: method_descriptor
  isModal: method_descriptor
  isRightToLeft: method_descriptor
  isTopLevel: method_descriptor
  isVisible: method_descriptor
  isVisibleTo: method_descriptor
  isWindow: method_descriptor
  isWindowModified: method_descriptor
  keyPressEvent: method_descriptor
  keyReleaseEvent: method_descriptor
  keyboardGrabber: staticmethod
  layout: method_descriptor
  layoutDirection: method_descriptor
  leaveEvent: method_descriptor
  locale: method_descriptor
  lower: method_descriptor
  mapFrom: method_descriptor
  mapFromGlobal: method_descriptor
  mapFromParent: method_descriptor
  mapTo: method_descriptor
  mapToGlobal: method_descriptor
  mapToParent: method_descriptor
  mask: method_descriptor
  maximumHeight: method_descriptor
  maximumSize: method_descriptor
  maximumWidth: method_descriptor
  metric: method_descriptor
  minimumHeight: method_descriptor
  minimumSize: method_descriptor
  minimumSizeHint: method_descriptor
  minimumWidth: method_descriptor
  mouseDoubleClickEvent: method_descriptor
  mouseGrabber: staticmethod
  mouseMoveEvent: method_descriptor
  mousePressEvent: method_descriptor
  mouseReleaseEvent: method_descriptor
  move: method_descriptor
  moveEvent: method_descriptor
  nativeEvent: method_descriptor
  nativeParentWidget: method_descriptor
  nextInFocusChain: method_descriptor
  normalGeometry: method_descriptor
  overrideWindowFlags: method_descriptor
  overrideWindowState: method_descriptor
  paintEngine: method_descriptor
  paintEvent: method_descriptor
  palette: method_descriptor
  parentWidget: method_descriptor
  pos: method_descriptor
  previousInFocusChain: method_descriptor
  raise_: method_descriptor
  rect: method_descriptor
  redirected: method_descriptor
  releaseKeyboard: method_descriptor
  releaseMouse: method_descriptor
  releaseShortcut: method_descriptor
  removeAction: method_descriptor
  render: method_descriptor
  repaint: method_descriptor
  resize: method_descriptor
  resizeEvent: method_descriptor
  restoreGeometry: method_descriptor
  saveGeometry: method_descriptor
  screen: method_descriptor
  scroll: method_descriptor
  setAcceptDrops: method_descriptor
  setAccessibleDescription: method_descriptor
  setAccessibleName: method_descriptor
  setAttribute: method_descriptor
  setAutoFillBackground: method_descriptor
  setBackgroundRole: method_descriptor
  setBaseSize: method_descriptor
  setContentsMargins: method_descriptor
  setContextMenuPolicy: method_descriptor
  setCursor: method_descriptor
  setDisabled: method_descriptor
  setEnabled: method_descriptor
  setFixedHeight: method_descriptor
  setFixedSize: method_descriptor
  setFixedWidth: method_descriptor
  setFocus: method_descriptor
  setFocusPolicy: method_descriptor
  setFocusProxy: method_descriptor
  setFont: method_descriptor
  setForegroundRole: method_descriptor
  setGeometry: method_descriptor
  setGraphicsEffect: method_descriptor
  setHidden: method_descriptor
  setInputMethodHints: method_descriptor
  setLayout: method_descriptor
  setLayoutDirection: method_descriptor
  setLocale: method_descriptor
  setMask: method_descriptor
  setMaximumHeight: method_descriptor
  setMaximumSize: method_descriptor
  setMaximumWidth: method_descriptor
  setMinimumHeight: method_descriptor
  setMinimumSize: method_descriptor
  setMinimumWidth: method_descriptor
  setMouseTracking: method_descriptor
  setPalette: method_descriptor
  setParent: method_descriptor
  setScreen: method_descriptor
  setShortcutAutoRepeat: method_descriptor
  setShortcutEnabled: method_descriptor
  setSizeIncrement: method_descriptor
  setSizePolicy: method_descriptor
  setStatusTip: method_descriptor
  setStyle: method_descriptor
  setStyleSheet: method_descriptor
  setTabOrder: staticmethod
  setTabletTracking: method_descriptor
  setToolTip: method_descriptor
  setToolTipDuration: method_descriptor
  setUpdatesEnabled: method_descriptor
  setVisible: method_descriptor
  setWhatsThis: method_descriptor
  setWindowFilePath: method_descriptor
  setWindowFlag: method_descriptor
  setWindowFlags: method_descriptor
  setWindowIcon: method_descriptor
  setWindowIconText: method_descriptor
  setWindowModality: method_descriptor
  setWindowModified: method_descriptor
  setWindowOpacity: method_descriptor
  setWindowRole: method_descriptor
  setWindowState: method_descriptor
  setWindowTitle: method_descriptor
  sharedPainter: method_descriptor
  show: method_descriptor
  showEvent: method_descriptor
  showFullScreen: method_descriptor
  showMaximized: method_descriptor
  showMinimized: method_descriptor
  showNormal: method_descriptor
  size: method_descriptor
  sizeHint: method_descriptor
  sizeIncrement: method_descriptor
  sizePolicy: method_descriptor
  stackUnder: method_descriptor
  statusTip: method_descriptor
  style: method_descriptor
  styleSheet: method_descriptor
  tabletEvent: method_descriptor
  testAttribute: method_descriptor
  toolTip: method_descriptor
  toolTipDuration: method_descriptor
  topLevelWidget: method_descriptor
  underMouse: method_descriptor
  ungrabGesture: method_descriptor
  unsetCursor: method_descriptor
  unsetLayoutDirection: method_descriptor
  unsetLocale: method_descriptor
  update: method_descriptor
  updateGeometry: method_descriptor
  updateMicroFocus: method_descriptor
  updatesEnabled: method_descriptor
  visibleRegion: method_descriptor
  whatsThis: method_descriptor
  wheelEvent: method_descriptor
  width: method_descriptor
  winId: method_descriptor
  window: method_descriptor
  windowFilePath: method_descriptor
  windowFlags: method_descriptor
  windowHandle: method_descriptor
  windowIcon: method_descriptor
  windowIconText: method_descriptor
  windowModality: method_descriptor
  windowOpacity: method_descriptor
  windowRole: method_descriptor
  windowState: method_descriptor
  windowTitle: method_descriptor
  windowType: method_descriptor
  x: method_descriptor
  y: method_descriptor
  RenderFlag: EnumType
  windowIconTextChanged: Signal
  windowIconChanged: Signal
  customContextMenuRequested: Signal
  windowTitleChanged: Signal
  staticMetaObject: QMetaObject

  # Namespace contribution from QObject
  blockSignals: method_descriptor
  childEvent: method_descriptor
  children: method_descriptor
  connect: staticmethod
  connectNotify: method_descriptor
  customEvent: method_descriptor
  deleteLater: method_descriptor
  disconnect: staticmethod
  disconnectNotify: method_descriptor
  dumpObjectInfo: method_descriptor
  dumpObjectTree: method_descriptor
  dynamicPropertyNames: method_descriptor
  emit: method_descriptor
  event: method_descriptor
  eventFilter: method_descriptor
  findChild: method_descriptor
  findChildren: method_descriptor
  inherits: method_descriptor
  installEventFilter: method_descriptor
  isQuickItemType: method_descriptor
  isSignalConnected: method_descriptor
  isWidgetType: method_descriptor
  isWindowType: method_descriptor
  killTimer: method_descriptor
  metaObject: method_descriptor
  moveToThread: method_descriptor
  objectName: method_descriptor
  parent: method_descriptor
  property: method_descriptor
  receivers: method_descriptor
  removeEventFilter: method_descriptor
  sender: method_descriptor
  senderSignalIndex: method_descriptor
  setObjectName: method_descriptor
  setParent: method_descriptor
  setProperty: method_descriptor
  signalsBlocked: method_descriptor
  startTimer: method_descriptor
  thread: method_descriptor
  timerEvent: method_descriptor
  tr: classmethod_descriptor
  objectNameChanged: Signal
  destroyed: Signal
  staticMetaObject: QMetaObject

# Namespace contribution from Object
